//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace AI_ERP.Application_Modules.EDUCATION.Elearning {
    
    
    public partial class wf_Ortu_UangSekolah {
        
        /// <summary>
        /// lblJumlahTagihan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblJumlahTagihan;
        
        /// <summary>
        /// ltrListBiayaSekolah control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltrListBiayaSekolah;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new AI_ERP.Application_Masters.Main Master {
            get {
                return ((AI_ERP.Application_Masters.Main)(base.Master));
            }
        }
    }
}
