//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AI_ERP.svcFileFoto {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="svcFileFoto.FileFotoSoap")]
    public interface FileFotoSoap {
        
        // CODEGEN: Generating message contract since element name nis from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LokasiFileFotoSiswa", ReplyAction="*")]
        AI_ERP.svcFileFoto.LokasiFileFotoSiswaResponse LokasiFileFotoSiswa(AI_ERP.svcFileFoto.LokasiFileFotoSiswaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LokasiFileFotoSiswaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LokasiFileFotoSiswa", Namespace="http://tempuri.org/", Order=0)]
        public AI_ERP.svcFileFoto.LokasiFileFotoSiswaRequestBody Body;
        
        public LokasiFileFotoSiswaRequest() {
        }
        
        public LokasiFileFotoSiswaRequest(AI_ERP.svcFileFoto.LokasiFileFotoSiswaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LokasiFileFotoSiswaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nis;
        
        public LokasiFileFotoSiswaRequestBody() {
        }
        
        public LokasiFileFotoSiswaRequestBody(string nis) {
            this.nis = nis;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LokasiFileFotoSiswaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LokasiFileFotoSiswaResponse", Namespace="http://tempuri.org/", Order=0)]
        public AI_ERP.svcFileFoto.LokasiFileFotoSiswaResponseBody Body;
        
        public LokasiFileFotoSiswaResponse() {
        }
        
        public LokasiFileFotoSiswaResponse(AI_ERP.svcFileFoto.LokasiFileFotoSiswaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LokasiFileFotoSiswaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LokasiFileFotoSiswaResult;
        
        public LokasiFileFotoSiswaResponseBody() {
        }
        
        public LokasiFileFotoSiswaResponseBody(string LokasiFileFotoSiswaResult) {
            this.LokasiFileFotoSiswaResult = LokasiFileFotoSiswaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FileFotoSoapChannel : AI_ERP.svcFileFoto.FileFotoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileFotoSoapClient : System.ServiceModel.ClientBase<AI_ERP.svcFileFoto.FileFotoSoap>, AI_ERP.svcFileFoto.FileFotoSoap {
        
        public FileFotoSoapClient() {
        }
        
        public FileFotoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileFotoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileFotoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileFotoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AI_ERP.svcFileFoto.LokasiFileFotoSiswaResponse AI_ERP.svcFileFoto.FileFotoSoap.LokasiFileFotoSiswa(AI_ERP.svcFileFoto.LokasiFileFotoSiswaRequest request) {
            return base.Channel.LokasiFileFotoSiswa(request);
        }
        
        public string LokasiFileFotoSiswa(string nis) {
            AI_ERP.svcFileFoto.LokasiFileFotoSiswaRequest inValue = new AI_ERP.svcFileFoto.LokasiFileFotoSiswaRequest();
            inValue.Body = new AI_ERP.svcFileFoto.LokasiFileFotoSiswaRequestBody();
            inValue.Body.nis = nis;
            AI_ERP.svcFileFoto.LokasiFileFotoSiswaResponse retVal = ((AI_ERP.svcFileFoto.FileFotoSoap)(this)).LokasiFileFotoSiswa(inValue);
            return retVal.Body.LokasiFileFotoSiswaResult;
        }
    }
}
